curl -X POST "https://accounts.spotify.com/api/token" \
     -H "Content-Type: application/x-www-form-urlencoded" \
     -d "grant_type=client_credentials&client_id=da242dbc68b1456cad8fc0cbac5bac53&client_secret=9bc8abd41f054b05a471f15e512efc1a"
